# Generated by Django 4.2.7 on 2023-11-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superusuario',
            name='cpf',
        ),
        migrations.AlterField(
            model_name='superusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
