# Generated by Django 4.2.7 on 2023-11-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_usuariotask_registro_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
